---
title: 'FGC_0005 Analysis'
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
---

# Setup

```{r,echo=F}
options(warn=-1)

suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(ggplot2))
suppressMessages(library(GGally))
suppressMessages(library(dplyr))
suppressMessages(library(perept))
suppressMessages(library(GICC))
suppressMessages(library(crispRutils))
suppressMessages(library(patchwork))

filter <- dplyr::filter
select <- dplyr::select
rename <- dplyr::rename
mutate <- dplyr::mutate

load("../data/ess.genes.rda")
mod_fitness.genes <- readRDS(file="../data/depmap_lfc_modfitn.rds")
val_data <- readRDS(file="../data/fgc0005_val-data.rds")$samples

# Slow to run from scratch.
desir_perf.depl <- readRDS(file="../data/desir_fdr_perf_depleted.rds")
mle_desir_0.8.depl <- readRDS(file="../data/mle_depleted_desir_thresh_0.8.rds")

perc_transd.preantibiotic <- data.frame(cell_line = c("SW480","RKO","HT-29","HCT116"),
                                        percent_transduction.preantibiotic = c(25,22.5,15,30),
                                        min_split_cell_count = c(175e6,135e6,135e6,110e6))

# Data kept locally.
mageck_files <- list.files("~/data/az_cruk/cdc7", 
                           pattern = "Treatment_vs_Control.gene_summary.txt", recursive = T, full.names = T)
mageck_files.cvp <- list.files("~/data/az_cruk/cdc7", 
                           pattern = "Control_vs_Plasmid.gene_summary.txt", recursive = T, full.names = T)
mageck_files.sgrna.cvp <- list.files("~/data/az_cruk/cdc7", 
                           pattern = "Control_vs_Plasmid.sgrna_summary.txt", recursive = T, full.names = T)

count_files <- list.files("~/data/az_cruk/cdc7", pattern="combined_counts.txt", recursive=T, full.names=T)
desir_files <- list.files("~/data/az_cruk/cdc7", 
                          pattern = "DesirabilityGeneRanking.tsv", recursive = T, full.names = T)
bagel_files.ctrl_pl <- list.files("~/data/az_cruk/cdc7",
                          pattern = "Control_vs_Plasmid.bf", recursive = T, full.names = T)
bagel_files.treat_pl <- list.files("~/data/az_cruk/cdc7",
                          pattern = "Treatment_vs_Plasmid.bf", recursive = T, full.names = T)


read_gene_summ <- function(files, type = "mageck"){
  ret <- NULL
  for(file in files){
    cell_line <- gsub("^.*?Comp-(\\S+?)\\/.*$","\\1",file)
    if(type == "mageck"){
      td <- read.table(file, header=T, stringsAsFactors = F) %>%
        select(id, neg.score, neg.p.value, neg.fdr, neg.rank, neg.lfc, pos.score, pos.p.value, pos.fdr, pos.rank, pos.lfc) %>%
        rename(gene = id)
    }else{
      td <- read.delim(file, header=T, stringsAsFactors = F) %>%
        select(gene, TvCCvP_PositiveDesi, TvCCvP_NegativeDesi, TvC_negpval, TvC_pospval, TvC_LFC)
    }
    ret <- rbind(ret, data.frame(cell_line = cell_line,td), stringsAsFactors=F)
  }
  return(ret)
}


read_bagel_output <- function(files, ess = "hart"){
  ret <- NULL
  if(length(ess)>1){
    ess_genes <- ess
  }else if(ess == "hart"){
    ess_genes <- ess.genes$bagel_essential
  }else if(ess == "sanger"){
    ess_genes <- ess.genes$pan_cancer_Sanger
  }else{
    stop(paste("unknown essentiality option",ess))
  }
  for(file in files){
    cell_line <- gsub("^.*?Comp-(\\S+?)\\/.*$","\\1",file)
    td <- read.table(file, header=T, stringsAsFactors = F) %>%
      filter(GENE %in% c(ess_genes, ess.genes$bagel_nonessential)) %>%
      mutate(TP = GENE %in% ess_genes,
             cell_line = cell_line) %>%
      add_ROC(score_col = "BF")
    ret <- rbind(ret, td)
  }
  return(ret)
}


norm_counts <- function(data, type){
  samples <- colnames(data)[grepl("^FGC",colnames(data))]
  samples <- samples[samples %in% val_data$name[val_data$class==type]]
  csums <- colSums(data[,3:ncol(data)])
  # Use median of controls for scaling normalized data.
  mdn.ctrl <- median(csums[grepl("FGC",names(csums))])
  data.norm <- data %>%
    mutate(!!sym(samples[1]) := mdn.ctrl * !!sym(samples[1])/csums[names(csums)==samples[1]],
         !!sym(samples[2]) := mdn.ctrl * !!sym(samples[2])/csums[names(csums)==samples[2]],
         Yusa_v3_KO_Plasmid_FGC_batch_1 = mdn.ctrl*Yusa_v3_KO_Plasmid_FGC_batch_1/csums[names(csums)=="Yusa_v3_KO_Plasmid_FGC_batch_1"],
         gene_group = case_when(gene %in% ess.genes$bagel_essential ~ "essential_Hart",
                                gene %in% ess.genes$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                gene %in% ess.genes$bagel_nonessential ~ "non_essential_Hart",
                                gene %in% mod_fitness.genes ~ "moderately_negative",
                                TRUE ~ "Other"))
  if(length(samples) == 3){
    data.norm %<>%
      mutate(!!sym(samples[3]) := mdn.ctrl * !!sym(samples[3])/csums[names(csums)==samples[3]])
  }
  return(data.norm)
}


read_counts <- function(files, type){
  ret <- list()
  for(file in files){
    comp <- gsub("^.*?/Comp-(\\S+?).counts.*$","\\1",file)
    ret[[comp]] <- read.delim(file) %>%
      norm_counts(type)
  }
  return(ret)
}


read_mageck_sgrna <- function(files){
  ret <- NULL
  for(file in files){
    cell_line <- gsub("^.*?Comp-(\\S+?)\\/.*$","\\1",file)
    td <- read.delim(file, header=T, stringsAsFactors = F, sep="\t") %>%
      mutate(cell_line = cell_line) %>%
      # Calculate log fold change for each Ctrl-Pl replicate pair.
      rowwise() %>%
      mutate(tr_count_1 = as.numeric(unlist(strsplit(treatment_count,"/"))[1]),
             tr_count_2 = as.numeric(unlist(strsplit(treatment_count,"/"))[2]),
             tr_lfc_1 = log2(tr_count_1) - log2(control_count),
             tr_lfc_2 = log2(tr_count_2) - log2(control_count)) %>%
      ungroup() %>%
      select(cell_line, sgrna, Gene, control_count, treatment_count, tr_count_1, tr_count_2, tr_lfc_1, tr_lfc_2)
    ret <- rbind(ret, td)
  }
  return(ret)
}


# For assessing cell line LFC similarities.
jaccard_index <- function(genes, data_1, data_2, thresh){
  jacc_num <- length(intersect(genes[data_1 < thresh], genes[data_2 < thresh]))
  jacc_denom <- length(union(genes[data_1 < thresh], genes[data_2 < thresh]))
  return(jacc_num/jacc_denom)
}

```


```{r}
data.mageck <- read_gene_summ(mageck_files)
data.mageck.cvp <- read_gene_summ(mageck_files.cvp)
data.desir <- read_gene_summ(desir_files, type = "desir")
data.bagel.ctrl_pl.hart <- read_bagel_output(bagel_files.ctrl_pl)
data.bagel.treat_pl.hart <- read_bagel_output(bagel_files.treat_pl)
data.bagel.ctrl_pl.sang <- read_bagel_output(bagel_files.ctrl_pl, ess="sanger")
data.bagel.treat_pl.sang <- read_bagel_output(bagel_files.treat_pl, ess="sanger")
data.bagel.ctrl_pl.mf <- read_bagel_output(bagel_files.ctrl_pl, ess=mod_fitness.genes)
data.bagel.treat_pl.mf <- read_bagel_output(bagel_files.treat_pl, ess=mod_fitness.genes)

data.counts.bl <- read_counts(count_files, type = "baseline")
data.counts.ctrl <- read_counts(count_files, type = "control")
data.counts.trt <- read_counts(count_files, type = "treatment")
```

# QC

## GICC of normalized counts

```{r}
run_gicc <- function(data){
  samps <- colnames(data)[3:(ncol(data)-1)]
  samps[grepl("^FGC",samps)] <- "control"
  td <- data.frame(id = samps, t(data[,3:(ncol(data)-1)]), stringsAsFactors = F)
  gicc <- GICC(td)
  return(gicc$GICC$GICC.1)
}

calc_gicc <- function(data_list){
  ret <- NULL
  for(comp in names(data_list)){
    td <- data_list[[comp]] %>%
      filter(gene_group != "Other") %>%
      group_by(gene_group) %>%
      do(data.frame(cell_line = comp, GICC = run_gicc(.), stringsAsFactors = F))
    ret <- rbind(ret, td)
  }
  return(ret)
}

```

```{r}
gicc.counts <- rbind(calc_gicc(data.counts.bl) %>%
                       mutate(time_point = "baseline"),
                     calc_gicc(data.counts.ctrl) %>%
                       mutate(time_point = "control"),
                     calc_gicc(data.counts.trt) %>%
                       mutate(time_point = "treatment")) %>%
  mutate(Percent_Transduction_PreAntibiotic = perc_transd.preantibiotic$percent_transduction.preantibiotic[match(cell_line,perc_transd.preantibiotic$cell_line)],
         Minimum_Split_Cell_Count = perc_transd.preantibiotic$min_split_cell_count[match(cell_line,perc_transd.preantibiotic$cell_line)])

gicc.counts %>% 
  ggplot(aes(cell_line, GICC, group=gene_group, color=gene_group)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype = "dashed") +
  facet_grid(~time_point) +
  ggtitle("Reproducibility of normalized counts: GICC")

gicc.counts %>%
  filter(time_point == "baseline" & gene_group != "non_essential_Hart") %>%
  ggplot(aes(Percent_Transduction_PreAntibiotic, GICC, color = gene_group, group = gene_group, 
             shape = cell_line)) +
  geom_point(size=4) +
  geom_line() +
  facet_grid(~time_point) +
  ggtitle("Baseline: GICC vs Percent Transduction PreAntibiotic")

gicc.counts %>%
  filter(time_point == "control" & gene_group != "non_essential_Hart") %>%
  ggplot(aes(Minimum_Split_Cell_Count, GICC, color = gene_group, group = gene_group, 
             shape = cell_line)) +
  geom_point(size=4) +
  geom_line() +
  facet_grid(~time_point) +
  ggtitle("Control: GICC vs Minimum Split Cell Count")

```

## LFC

```{r}
data.mageck.cvp %>%
  mutate(gene_group = case_when(gene %in% ess.genes$bagel_essential ~ "essential_Hart",
                                gene %in% ess.genes$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                gene %in% ess.genes$bagel_nonessential ~ "non_essential_Hart",
                                gene %in% mod_fitness.genes ~ "moderately_negative",
                                TRUE ~ "Other")) %>%
  filter(gene_group != "Other") %>%
  ggplot(aes(cell_line, neg.lfc, color = gene_group)) +
  geom_point(position = position_dodge(width=0.75)) +
  geom_boxplot(notch=T) +
  geom_hline(yintercept = 0, linetype="dashed") +
  ylab("Log2 Fold Change") +
  ggtitle("Log fold change: cell line and gene set comparison")

```


```{r}
## NNMD
nnmd <- rbind(
  data.mageck.cvp %>%
    group_by(cell_line) %>%
    do(data.frame(NNMD = calc_NNMD(., "gene", "neg.lfc", ess.genes$pan_cancer_Sanger, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "gene", "neg.lfc", 
                                      ess.genes$pan_cancer_Sanger, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "pan_cancer_Sanger"),
  data.mageck.cvp %>%
    group_by(cell_line) %>%
    do(data.frame(NNMD = calc_NNMD(., "gene", "neg.lfc", ess.genes$bagel_essential, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "gene", "neg.lfc", 
                                      ess.genes$bagel_essential, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "essential_Hart"),
  data.mageck.cvp %>%
    group_by(cell_line) %>%
    do(data.frame(NNMD = calc_NNMD(., "gene", "neg.lfc", mod_fitness.genes, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "gene", "neg.lfc", 
                                      mod_fitness.genes, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "moderately_negative")
)


nnmd %>%
  ggplot(aes(cell_line, NNMD, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ggtitle("LFC NNMD: Control vs Plasmid")

nnmd %>%
  ggplot(aes(cell_line, NNMD_robust, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ggtitle("LFC NNMD robust: Control vs Plasmid")

```

## ROC

```{r}
ggplot(data.bagel.ctrl_pl.hart,
       aes(False_Positive_Rate, True_Positive_Rate, color=cell_line)) +
  geom_line() +
  geom_abline(linetype="dashed") +
  ggtitle("ROC Hart essentials: Control vs Plasmid")

ggplot(data.bagel.treat_pl.hart,
       aes(False_Positive_Rate, True_Positive_Rate, color=cell_line)) +
  geom_line() +
  geom_abline(linetype="dashed") +
  ggtitle("ROC Hart essentials: Treatment vs Plasmid")

ggplot(data.bagel.ctrl_pl.sang,
       aes(False_Positive_Rate, True_Positive_Rate, color=cell_line)) +
  geom_line() +
  geom_abline(linetype="dashed") +
  ggtitle("ROC Sanger pan-cancer: Control vs Plasmid")

ggplot(data.bagel.treat_pl.sang,
       aes(False_Positive_Rate, True_Positive_Rate, color=cell_line)) +
  geom_line() +
  geom_abline(linetype="dashed") +
  ggtitle("ROC Sanger pan-cancer: Treatment vs Plasmid")

```

## Precision-Recall

```{r}
pr.hart <- data.bagel.ctrl_pl.hart %>%
  group_by(cell_line) %>%
  do(data.frame(get_PRROC(., "BF", group_col = "cell_line")))

pr.sang <- data.bagel.ctrl_pl.sang %>%
  group_by(cell_line) %>%
  do(data.frame(get_PRROC(., "BF", group_col = "cell_line")))

pr.mf <- data.bagel.ctrl_pl.mf %>%
  group_by(cell_line) %>%
  do(data.frame(get_PRROC(., "BF", group_col = "cell_line")))

# Plots.
ggplot(pr.hart, aes(Recall,Precision,color=cell_line, group=cell_line)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  ggtitle("Precision-Recall: Hart essentials")

ggplot(pr.sang, aes(Recall,Precision,color=cell_line, group=cell_line)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  ggtitle("Precision-Recall: pan-cancer Sanger")

ggplot(pr.mf, aes(Recall,Precision,color=cell_line, group=cell_line)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  ggtitle("Precision-Recall: moderately negative fitness defects")

plot.auprrc <- rbind(pr.sang %>%
                  group_by(cell_line) %>%
                  summarise(AUPrRc = AUPrRc[1]) %>%
                  mutate(gene_group = "pan_cancer_Sanger"),
                pr.hart %>%
                  group_by(cell_line) %>%
                  summarise(AUPrRc = AUPrRc[1]) %>%
                  mutate(gene_group = "essential_Hart"),
                pr.mf %>%
                  group_by(cell_line) %>%
                  summarise(AUPrRc = AUPrRc[1]) %>%
                  mutate(gene_group = "moderately_negative")) %>%
  ggplot(aes(cell_line, AUPrRc, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  ggtitle("AUC Precision-Recall: cell line and gene set comparison")

plot.fdr_prrc <- rbind(pr.sang %>%
                  group_by(cell_line) %>%
                  summarise(Sensitivity_fdr_10pct = Sensitivity_fdr_10pct[1]) %>%
                  mutate(gene_group = "pan_cancer_Sanger"),
                pr.hart %>%
                  group_by(cell_line) %>%
                  summarise(Sensitivity_fdr_10pct = Sensitivity_fdr_10pct[1]) %>%
                  mutate(gene_group = "essential_Hart"),
                pr.mf %>%
                  group_by(cell_line) %>%
                  summarise(Sensitivity_fdr_10pct = Sensitivity_fdr_10pct[1]) %>%
                  mutate(gene_group = "moderately_negative")) %>%
  ggplot(aes(cell_line, Sensitivity_fdr_10pct, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  ggtitle("Sensitivity at 10% FDR: cell line and gene set comparison")

plot.auprrc / plot.fdr_prrc

```

# Cell line analysis

```{r}
# Jaccard index for negative LFC
ji <- data.desir %>%
  tidyr::pivot_wider(id_cols = gene, names_from = cell_line,
                     values_from = TvC_LFC) %>%
  rowwise() %>%
  mutate(median.lfc = median(c(HCT116,`HT-29`,RKO,SW480), na.rm=T)) %>%
  ungroup() %>%
  arrange(median.lfc) %>%
  head(n=150)
  
jd <- c(jaccard_index(ji$gene, ji$`HT-29`, ji$HCT116, -0.25),
        jaccard_index(ji$gene, ji$`HT-29`, ji$SW480, -0.25),
        jaccard_index(ji$gene, ji$`HT-29`, ji$RKO, -0.25),
        jaccard_index(ji$gene, ji$HCT116, ji$SW480, -0.25),
        jaccard_index(ji$gene, ji$HCT116, ji$RKO,-0.25),
        jaccard_index(ji$gene, ji$SW480, ji$RKO, -0.25))
jacc.mat <- matrix(c(1,jd[1:3],
                         jd[1],1,jd[4:5],
                         jd[c(2,4)],1,jd[6],
                         jd[c(3,5,4)],1), 4, 4, byrow = T)
colnames(jacc.mat) <- rownames(jacc.mat) <- c("HT-29","HCT116","SW480","RKO")

ggcorr(jacc.mat, label = T, label_round = 3, cor_matrix = jacc.mat, limits=c(0.25,0.6),
       midpoint = 0.4) +
  labs(title = "Cell line log-fold-change (LFC) similarity:",
       subtitle =  "Jaccard Index for top 150 negative LFC genes")

```


# Performance MLE: Choosing score cutoffs on basis of FPR estimates

## Desirability scores

```{r}
# Put data into format needed by 'MLE.perept'.
prep_4_mle <- function(data, desir_thresh, dcol_name = "TvCCvP_NegativeDesi"){
  dcol <- sym(dcol_name)
  data %<>%
      mutate(hit = !!dcol >= desir_thresh) %>%
      tidyr::pivot_wider(id_cols = c(cell_line, gene), names_from = cell_line, values_from = hit) %>%
      dplyr::rowwise() %>%
      mutate(total = sum(c(HCT116, `HT-29`, RKO, SW480))) %>%
      dplyr::ungroup() %>%
      filter(!is.na(total) & gene != "Control")
  return(data)
}

# Find desirability threshold that corresponds to FDR of X%.
fix_FDR.desir <- function(data, start_desir = 0.9, stop_desir = NULL, fdr_thresh = 0.1, type = "negative", step_size = 0.1){
  if(type == "negative"){
    data %<>%
      select(cell_line, gene, TvCCvP_NegativeDesi)
    dcol <- "TvCCvP_NegativeDesi"
  }else{
    data %<>%
      select(cell_line, gene, TvCCvP_PositiveDesi)
    dcol <- "TvCCvP_PositiveDesi"
  }
  desir_thresh <- start_desir
  finish <- FALSE
  track_perf <- NULL
  while(!finish){
    cat("Desirability Threshold:",desir_thresh,"\n")
    td <- prep_4_mle(data, desir_thresh, dcol_name = dcol)
    mle <- MLE.perept(as.data.frame(td))
    # Estimate of global FDR.
    num_TP <- mle$prevalence$theta_1*nrow(td)
    num_TN <- nrow(td)-num_TP
    num_FP <- mle$performance$p10*num_TN
    FDR <- num_FP/(num_FP+num_TP)
    # Estimate of FDR after excluding singletons.
    if(length(which(td$total>=2))==0){
      # No shared hits.
      FDR.comm <- 0
      prob_pos_2 <- 0
    }else{
      prob_two_false <- 1-mle$delta$delta_pos[which(td$total==2)[1]]
      prob_three_false <- 1-mle$delta$delta_pos[which(td$total==3)[1]]
      num_two_false <- round(length(which(td$total==2))*prob_two_false)
      num_three_false <- round(length(which(td$total==3))*prob_three_false)
      FDR.comm <- (num_two_false + num_three_false)/(length(which(td$total>=2)))
      prob_pos_2 <- mle$delta$delta_pos[which(td$total==2)[1]]
    }
    track_perf <- rbind(track_perf, data.frame(Desir_threshold = desir_thresh,
                                               FPR = mle$performance$p10,
                                               FDR.global = FDR,
                                               FDR.common = FDR.comm,
                                               Sensitivity = mle$performance$p11,
                                               Prevalence = round(mle$prevalence$theta_1*nrow(td)),
                                               Prob_pos.two_shared_hits = prob_pos_2,
                                               Number_singletons = length(which(td$total==1)),
                                               Number_common_hits = length(which(td$total>=2))))
    if(!is.null(stop_desir)){
      if(desir_thresh <= stop_desir){
        finish <- TRUE
        ret <- td %>%
        mutate(probability_hit = mle$delta$delta_pos)
      }
    }
    if(FDR.comm >= fdr_thresh){
      finish <- TRUE
      ret <- td %>%
        mutate(probability_hit = mle$delta$delta_pos)
    }else{
      desir_thresh <- desir_thresh - step_size
    }
  }
  return(list(data = ret, perf = track_perf))
}

```

### Depleted

```{r, eval=F}
fdr.desir <- fix_FDR.desir(data.desir)
fdr.desir.sp <- fix_FDR.desir(data.desir, start_desir = 0.8, step_size = 0.01)

```

```{r}
depl_candidates <-  prep_4_mle(data.desir,0.8) %>%
  mutate(probability_hit = mle_desir_0.8.depl$delta$delta_pos,
         gene_hit = probability_hit > 0.5)

# Singleton hits.
singleton_hits <- setdiff((data.mageck %>%
  filter(neg.fdr <= 0.1))$gene, depl_candidates$gene[depl_candidates$gene_hit])

```

```{r}
ggplot(desir_perf.depl, aes(Desir_threshold, FDR)) +
  geom_point() +
  geom_smooth()


```


### Enriched

```{r, eval=F}
fdr.desir.enr <- fix_FDR.desir(data.desir, type="positive")
fdr.desir.sp <- fix_FDR.desir(data.desir, type="positive", start_desir = 0.7, step_size = 0.02)


```



