---
title: 'QC screen (HT-29 essentiality) analysis: FGC_0008 and FGC_0009'
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
---

# Setup

```{r,echo=F}
options(warn=-1)

suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(readr))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(fgcQC))


select <- dplyr::select
filter <- dplyr::filter

load("../data/ess.genes.rda")
mod_fitness.genes <- readRDS(file="~/data/az_cruk/depmap/depmap_lfc_modfitn.rds")
mouse_dnds.ess <- readRDS(file = "../data/mouse_dnds.essential_genes.rds")

data_base_path <- "~/data/az_cruk"

counts.8.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0008"), 
                                 pattern = "combined_counts.txt", recursive = T, full.names = T)

counts.9.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0009"), 
                                 pattern = "combined_counts.txt", recursive = T, full.names = T)

cleanr_lfc.8.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0008"), 
                                 pattern = "Control_vs_Plasmid_correctedFCs.tsv", recursive = T, full.names = T)

cleanr_lfc.9.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0009"), 
                                 pattern = "Control_vs_Plasmid_correctedFCs.tsv", recursive = T, full.names = T)

bagel.8.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0008"), 
                                 pattern = "Control_vs_Plasmid.bf", recursive = T, full.names = T)

bagel.9.files <- list.files(file.path(data_base_path,"QC_screen-FGC_0009"), 
                                 pattern = "Control_vs_Plasmid.bf", recursive = T, full.names = T)

# Read functions.
read_counts <- function(files, project_id){
  ret <- list()
  for(file in files){
    comp <- gsub("^.*?/(\\S+?_vs_plasmid.*?)/.*$","\\1",file)
    ret[[comp]] <- read.delim(file, header=T, stringsAsFactors = F)
  }
  return(ret)
}


read_cleanr_lfc <- function(files, project_id){
  ret <- NULL
  for(file in files){
    comp <- gsub("^.*?/(\\S+?_vs_plasmid.*?)/.*$","\\1",file)
    tp <- gsub("^(\\S+?)_.*$","\\1",comp)
    num_reps <- gsub("^.*?vs_plasmid_(._replicates.*)$","\\1",comp)
    ret <- rbind(ret, data.frame(read.delim(file, header=T, stringsAsFactors = F),
                                 project_id = project_id, comparison = comp, time_point = tp, 
                                 num_reps = num_reps, stringsAsFactors = F))
  }
  return(ret %>%
           mutate(gene_group = case_when(GENE %in% crispr_gene_sets$essential$hart_essential ~ "essential_Hart",
                                         GENE %in% crispr_gene_sets$essential$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                         GENE %in% crispr_gene_sets$essential$hart_nonessential ~ "non_essential_Hart",
                                         GENE %in% crispr_gene_sets$essential$moderately_negative ~ "moderately_negative",
                                         GENE %in% crispr_gene_sets$essential$weakly_negative ~ "weakly_negative",
                                         TRUE ~ "Other")))
}


read_bagel_output <- function(files, ess = "hart"){
  ret <- NULL
  if(length(ess)>1){
    ess_genes <- ess
  }else if(ess == "hart"){
    ess_genes <- ess.genes$bagel_essential
  }else if(ess == "sanger"){
    ess_genes <- ess.genes$pan_cancer_Sanger
  }else{
    stop(paste("unknown essentiality option",ess))
  }
  for(file in files){
    comp <- gsub("^.*?/(\\S+?_vs_plasmid.*?)/.*$","\\1",file)
    tp <- gsub("^(\\S+?)_.*$","\\1",comp)
    num_reps <- gsub("^.*?vs_plasmid_(._replicates.*)$","\\1",comp)
    td <- read.delim(file, header=T, stringsAsFactors = F) %>%
      filter(GENE %in% c(ess_genes, ess.genes$bagel_nonessential)) %>%
      mutate(TP = GENE %in% ess_genes,
             comparison = comp, time_point = tp,
             replicates = num_reps) %>%
      add_ROC(score_col = "BF")
    ret <- rbind(ret, td)
  }
  return(ret)
}


norm_counts <- function(data){
  samples <- colnames(data)[grepl("^FGC",colnames(data))]
  csums <- colSums(data[,3:ncol(data)])
  # Use median of controls for scaling normalized data.
  mdn.ctrl <- median(csums[grepl("FGC",names(csums))])
  data.norm <- data %>%
    mutate(!!sym(samples[1]) := mdn.ctrl * !!sym(samples[1])/csums[names(csums)==samples[1]],
         !!sym(samples[2]) := mdn.ctrl * !!sym(samples[2])/csums[names(csums)==samples[2]],
         Yusa_v3_KO_Plasmid_FGC_batch_1 = mdn.ctrl*Yusa_v3_KO_Plasmid_FGC_batch_1/csums[names(csums)=="Yusa_v3_KO_Plasmid_FGC_batch_1"],
         gene_group = case_when(gene %in% crispr_gene_sets$essential$hart_essential ~ "essential_Hart",
                                         gene %in% crispr_gene_sets$essential$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                         gene %in% crispr_gene_sets$essential$hart_nonessential ~ "non_essential_Hart",
                                         gene %in% crispr_gene_sets$essential$moderately_negative ~ "moderately_negative",
                                         gene %in% crispr_gene_sets$essential$weakly_negative ~ "weakly_negative",
                                TRUE ~ "Other"))
  if(length(samples) == 3){
    data.norm %<>%
      mutate(!!sym(samples[3]) := mdn.ctrl * !!sym(samples[3])/csums[names(csums)==samples[3]])
  }
  return(data.norm)
}


read_counts <- function(files){
  ret <- list()
  for(file in files){
    comp <- gsub("^.*?/(\\S+?_vs_plasmid.*?)/.*$","\\1",file)
    ret[[comp]] <- read.delim(file) %>%
      norm_counts()
  }
  return(ret)
}

```

```{r}
# Yusa v3 with gRNA sequences.
yusa.v3 <- read.delim("~/data/az_cruk/cleanr.tsv", stringsAsFactors = F, header=T) %>%
  rowwise() %>%
  mutate(GC_percent = 100*(sum(unlist(strsplit(seq,"")) == "G") + sum(unlist(strsplit(seq,"")) == "C"))/19,
         pam_upstream4 = substr(seq,16,19),
         proximal_4bases_pam = case_when(grepl("TT",pam_upstream4) ~ "TT",
                                         grepl("GCC",pam_upstream4) ~ "GCC",
                                         TRUE ~ "Other")) %>%
  ungroup()

```

```{r}
# Read data.
counts.8 <- read_counts(counts.8.files)
counts.9 <- read_counts(counts.9.files)

lfc_cleanr <- read_cleanr_lfc(cleanr_lfc.8.files, "FGC_0008") %>%
  rbind(read_cleanr_lfc(cleanr_lfc.9.files, "FGC_0009")) %>%
  mutate(time_point = factor(time_point, levels = c("baseline","d7","d14","d17"))) %>%
  left_join(yusa.v3, by = c("SEQID" = "CODE"))

data.bagel.hart.8 <- read_bagel_output(bagel.8.files, ess="hart")
data.bagel.hart.9 <- read_bagel_output(bagel.9.files, ess="hart")
data.bagel.sang.8 <- read_bagel_output(bagel.8.files, ess="sanger")
data.bagel.sang.9 <- read_bagel_output(bagel.9.files, ess="sanger")
data.bagel.mf.8 <- read_bagel_output(bagel.8.files, ess=crispr_gene_sets$essential$moderately_negative)
data.bagel.mf.9 <- read_bagel_output(bagel.9.files, ess=crispr_gene_sets$essential$moderately_negative)
data.bagel.wf.8 <- read_bagel_output(bagel.8.files, ess=crispr_gene_sets$essential$weakly_negative)
data.bagel.wf.9 <- read_bagel_output(bagel.9.files, ess=crispr_gene_sets$essential$weakly_negative)

```

# Moderately negative fitness defect gene group

```{r}
ggplot(mouse.dnds, aes(gene_group, dn_ds.mouse, color = gene_group)) +
  geom_point() +
  geom_boxplot(notch=T) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  ggtitle("dN/dS human-mouse: Essential gene groups")

```

# Reproducibility of counts

```{r}
run_gicc <- function(data){
  samps <- colnames(data)[3:(ncol(data)-1)]
  samps[grepl("^FGC",samps)] <- "control"
  td <- data.frame(id = samps, t(data[,3:(ncol(data)-1)]), stringsAsFactors = F)
  gicc <- GICC(td)
  return(gicc$GICC$GICC.1)
}

calc_gicc <- function(data_list){
  ret <- NULL
  for(comp in names(data_list)){
    tp <- gsub("^(\\S+?)_.*$","\\1",comp)
    num_reps <- gsub("^.*?vs_plasmid_(._replicates.*)$","\\1",comp)
    td <- data_list[[comp]] %>%
      filter(gene_group != "Other") %>%
      group_by(gene_group) %>%
      do(data.frame(comparison = comp, time_point = tp, num_reps = num_reps,
                    GICC = run_gicc(.), stringsAsFactors = F))
    ret <- rbind(ret, td)
  }
  return(ret)
}

```

```{r}
gicc.counts <- calc_gicc(counts.8) %>%
  mutate(project_id = "FGC_0008") %>%
  rbind(calc_gicc(counts.9) %>%
          mutate(project_id = "FGC_0009"))

gicc.counts %>% 
  filter(project_id == "FGC_0008") %>%
  mutate(time_point = factor(time_point,levels=c("baseline","d7","d14"))) %>%
  ggplot(aes(time_point, GICC, group=gene_group, color=gene_group)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype = "dashed") +
  facet_grid(~num_reps) +
  ggtitle("Reproducibility of normalized counts: FGC_0008, 2 vs 3 replicates")

gicc.counts %>%
  filter(comparison %in% c("d7_vs_plasmid_2_replicates_combn1","d7_vs_plasmid_QC")) %>%
  ggplot(aes(project_id, GICC, group=gene_group, color=gene_group)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0.6, linetype = "dashed") +
  facet_grid(~time_point) +
  ggtitle("Reproducibility of normalized counts: 2 replicates, Day 7")

```

# Log-fold change distributions

## 2 replicates

```{r}
lfc_cleanr %>%
  filter(gene_group != "Other" & (grepl("combn1",comparison) | grepl("QC",comparison))) %>%
  ggplot(aes(project_id, correctedFC, color = gene_group)) +
    geom_point(position = position_dodge(width=0.75)) +
    geom_boxplot(notch = T) +
    geom_hline(yintercept = 0, linetype="dashed") +
    facet_grid(~time_point) +
    ggtitle("logFC (corrected): 2 replicates")

```

## 2 vs 3 replicates

```{r}
lfc_cleanr %>%
  filter(gene_group != "Other" & project_id == "FGC_0008" & time_point == "d7") %>%
  ggplot(aes(num_reps, correctedFC, color = gene_group)) +
    geom_point(position = position_dodge(width=0.75)) +
    geom_boxplot(notch = T) +
    geom_hline(yintercept = 0, linetype="dashed") +
    facet_grid(time_point~num_reps, space="free_x", scales="free_x") +
    ggtitle("Day 7 logFC (corrected): FGC_0008: 2 vs 3 replicates")

```

## Null-normalized mean difference (NNMD)

```{r}
## NNMD
nnmd <- rbind(
  lfc_cleanr %>%
    group_by(comparison) %>%
    do(data.frame(project_id = .$project_id[1], time_point = .$time_point[1], num_reps = .$num_reps[1],
       NNMD = calc_NNMD(., "GENE", "correctedFC", ess.genes$pan_cancer_Sanger, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "GENE", "correctedFC", 
                                      ess.genes$pan_cancer_Sanger, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "pan_cancer_Sanger"),
  lfc_cleanr %>%
    group_by(comparison) %>%
    do(data.frame(project_id = .$project_id[1], time_point = .$time_point[1], num_reps = .$num_reps[1],
       NNMD = calc_NNMD(., "GENE", "correctedFC", ess.genes$bagel_essential, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "GENE", "correctedFC", 
                                      ess.genes$bagel_essential, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "essential_Hart"),
  lfc_cleanr %>%
    group_by(comparison) %>%
    do(data.frame(project_id = .$project_id[1], time_point = .$time_point[1], num_reps = .$num_reps[1],
       NNMD = calc_NNMD(., "GENE", "correctedFC", genes.mod_fitn, ess.genes$bagel_nonessential),
       NNMD_robust = calc_NNMD_robust(., "GENE", "correctedFC", 
                                      genes.mod_fitn, ess.genes$bagel_nonessential))) %>%
    ungroup() %>%
    mutate(gene_group = "moderately_negative")
)
  
nnmd %>%
  filter(project_id == "FGC_0008") %>%
  mutate(time_point = factor(time_point,levels=c("baseline","d7","d14"))) %>%
  ggplot(aes(time_point, NNMD, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  facet_grid(~num_reps) +
  ggtitle("NNMD: FGC_0008, 2 vs 3 replicates")

nnmd %>%
  filter(project_id == "FGC_0008") %>%
  mutate(time_point = factor(time_point,levels=c("baseline","d7","d14"))) %>%
  ggplot(aes(time_point, NNMD_robust, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  facet_grid(~num_reps) +
  ggtitle("NNMD robust: FGC_0008, 2 vs 3 replicates")

nnmd %>%
  filter(comparison %in% c("d7_vs_plasmid_2_replicates_combn1","d7_vs_plasmid_QC")) %>%
  ggplot(aes(project_id, NNMD, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  facet_grid(~time_point) +
  ggtitle("NNMD: 2 replicates, Day 7")

nnmd %>%
  filter(comparison %in% c("d7_vs_plasmid_2_replicates_combn1","d7_vs_plasmid_QC")) %>%
  ggplot(aes(project_id, NNMD_robust, group = gene_group, color = gene_group)) +
  geom_point() +
  geom_line() +
  facet_grid(~time_point) +
  ggtitle("NNMD robust: 2 replicates, Day 7")

```

## GC content

```{r}
lfc_cleanr %>%
  filter(comparison %in% c("d7_vs_plasmid_2_replicates_combn1","d7_vs_plasmid_QC") & between(GC_percent,20,75)) %>%
  mutate(GC_percent = factor(round(GC_percent))) %>%
  ggplot(aes(GC_percent, correctedFC, color=project_id)) + 
  geom_point(position = position_dodge(width=0.75)) + 
  geom_boxplot(notch=T) +
  ylim(-3,1.5) +
  geom_hline(yintercept = 0, linetype="dashed") +
  ggtitle("logFC Day 7 vs sgRNA GC content (2 replicates)")

```

# Bagel performance

## Precision-Recall

```{r}
pr.hart <- rbind(data.bagel.hart.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.hart.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

pr.sang <- rbind(data.bagel.sang.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.sang.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

pr.mf <- rbind(data.bagel.mf.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.mf.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

pr.wf <- rbind(data.bagel.wf.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.wf.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

roc.wf <- rbind(data.bagel.wf.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.wf.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

ggplot(pr.sang, aes(Recall,Precision,color=screen, group=replicates)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  ggtitle("Precision-Recall: Day 7, 2 reps, Sanger pan-cancer genes")

ggplot(pr.hart, aes(Recall,Precision,color=screen, group=replicates)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  geom_segment(aes(x = 0.75, y = 0.9, xend = -0.02, yend = 0.9), linetype = "dashed", color="black") +
  geom_segment(aes(x = 0.75, y = 0.3, xend = 0.75, yend = 0.9), linetype = "dashed", color="black") +
  geom_segment(aes(x = 0.746, y = 0.3, xend = 0.746, yend = 0.9), linetype = "dashed", color="black") +
  ggtitle("Precision-Recall: Day 7, 2 reps, Hart essentials")

ggplot(pr.mf, aes(Recall,Precision,color=screen, group=replicates)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  geom_segment(aes(x = 0.75, y = 0.9, xend = -0.02, yend = 0.9), linetype = "dashed", color="black") +
  geom_segment(aes(x = 0.75, y = 0.2, xend = 0.75, yend = 0.9), linetype = "dashed", color="black") +
  geom_segment(aes(x = 0.71, y = 0.2, xend = 0.71, yend = 0.9), linetype = "dashed", color="black") +
  ggtitle("Precision-Recall: Day 7, 2 reps, Moderately Negative fitness genes (DepMap)")

ggplot(pr.wf, aes(Recall,Precision,color=screen, group=replicates)) +
  geom_line() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  #geom_segment(aes(x = 0.75, y = 0.9, xend = -0.02, yend = 0.9), linetype = "dashed", color="black") +
  #geom_segment(aes(x = 0.71, y = 0.2, xend = 0.71, yend = 0.9), linetype = "dashed", color="black") +
  #geom_segment(aes(x = 0.75, y = 0.2, xend = 0.75, yend = 0.9), linetype = "dashed", color="black") +
  ggtitle("Precision-Recall: Day 7, 2 reps, Weakly Negative fitness genes (DepMap)")

pr.sang.later <- rbind(data.bagel.sang.8 %>%
                   filter(time_point == "d14") %>%
                   group_by(replicates) %>%
                   do(data.frame(Bget_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.sang.9 %>%
            filter(time_point == "d17") %>%
            group_by(replicates) %>% 
            do(data.frame(Bget_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

pr.hart.later <- rbind(data.bagel.hart.8 %>%
                   filter(time_point == "d14") %>%
                   group_by(replicates) %>%
                   do(data.frame(Bget_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.hart.9 %>%
            filter(time_point == "d17") %>%
            group_by(replicates) %>% 
            do(data.frame(Bget_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

pr.mf <- rbind(data.bagel.mf.8 %>%
                   filter(time_point == "d7") %>%
                   group_by(replicates) %>%
                   do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>% 
                   mutate(screen="08"),
          data.bagel.mf.9 %>%
            filter(time_point == "d7") %>%
            group_by(replicates) %>% 
            do(data.frame(get_PRROC(., "BF", group_col = "replicates"))) %>%
            mutate(screen="09"))

```

## Bayes Factor threshold of 6

```{r}
# All genes.
bagel.all.thresh <- read_bagel_output(bagel.8.files, ess=unique(yusa.v3$GENES)) %>%
  mutate(project_id = "FGC_0008") %>%
  rbind(data.bagel.all.9 <- read_bagel_output(bagel.9.files, ess=unique(yusa.v3$GENES)) %>%
          mutate(project_id = "FGC_0009")) %>%
  group_by(project_id, time_point, comparison) %>%
  summarise(Num_genes_above_BF_6 = length(which(BF >= 6))) %>%
  ungroup() %>%
  mutate(time_point = factor(time_point, levels=c("baseline","d7","d14","d17")))

bagel.all.thresh %>%
  filter((grepl("combn1",comparison) | grepl("QC",comparison))) %>%
  ggplot(aes(project_id, Num_genes_above_BF_6, fill = project_id)) +
  geom_bar(stat = "identity") +
  facet_grid(~time_point) +
  ggtitle("Number of genes with BF > 6: 2 replicates")

```


