---
title: 'TechDev_0001: MOI theoretical predictions'
author: "Alex Kalinka"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    depth: 3
    highlight: tango
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
---

# Setup

```{r,echo=F}
options(warn=-1)

suppressMessages(library(knitr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(splines2))
suppressMessages(library(patchwork))
suppressMessages(library(ashr))
suppressMessages(library(fgcQC))


filter <- dplyr::filter
select <- dplyr::select
rename <- dplyr::rename
mutate <- dplyr::mutate


rnap_fivemer <- read.csv("../data/rnap-II-yeast-fivemer-density.csv", stringsAsFactors = F)

yusa.v3.folds <- read.csv("../data/lib.yusa.v3-plus-scaffold-free-energy.csv", stringsAsFactors = F)

load("~/git-projects/crispRutils/data/yusa.v3.crisprn.annot.rda")

lib <- read.delim("~/git-projects/az-cruk-crispr-pipeline-referencedata/libraries/yusa_v3_human.1/cleanr.tsv",
                  header=F, skip=1, stringsAsFactors = F) %>%
  left_join(yusa.v3.folds, by = c("V2" = "id")) %>%
  mutate(GC_percent = 100*GC_fraction)

qc <- readRDS(file = "../data/qc_techdev_0001.rds") %>%
  #filter(!grepl("T",MOI)) %>%
  mutate(moi = MOI, MOI = as.numeric(gsub("[T/F]","",MOI)))


cleanr.files <- list.files("~/data/az_cruk/techdev_0001/", pattern = "Control_vs_Plasmid_correctedFCs.tsv",
                           full.names = T, recursive = T)
counts.files <- list.files("~/data/az_cruk/techdev_0001/", pattern = "combined_counts.txt",
                           full.names = T, recursive = T)

read_lfc <- function(files, type = "cleanr"){
  ret <- NULL
  for(file in files){
    if(!grepl("MOI",file)) next
    
    comp <- gsub(paste("^.*?(MOI.*)\\/",type,".*$",sep=""),"\\1",file)
    moi <- gsub("^MOI-(.*?)-.*$","\\1",comp)
    time <- gsub("^MOI-.*?-(.*)$","\\1",comp)

    td <- read.delim(file, header=T, stringsAsFactors = F, sep="\t")
    if(type != "cleanr"){    
      td %<>%
        rename(TECHDEV0001_plasmid = Yusa_v3_KO_Plasmid_FGC_batch_1) %>%
        pivot_longer(cols = starts_with("TECHDEV0001"), names_to = "sample_id", values_to = "count")
    }
    td %<>%
      mutate(comparison = comp, MOI = moi, time_point = time)
    ret <- rbind(ret, td)
  }
  return(ret)
}



lfc <- read_lfc(cleanr.files)
counts <- read_lfc(counts.files, type = "counts")


```


# Counts

```{r}
counts %>%
  filter(time_point == "day14") %>%
  ggplot(aes(MOI, count)) +
  geom_point() +
  geom_boxplot()

counts %>%
  filter(time_point == "day14" & gene %in% c(crispr_gene_sets$essential$pan_cancer_Sanger, 
                     crispr_gene_sets$essential$hart_nonessential)) %>%
  mutate(gene_group = ifelse(gene %in% crispr_gene_sets$essential$pan_cancer_Sanger, "pan_cancer_Sanger","hart_nonessential")) %>%
  ggplot(aes(MOI, count, color = gene_group)) +
  geom_point(position = position_dodge(width=0.75)) +
  geom_boxplot()


```

# logFC

## Essential vs Non-essential

```{r}
lfc.pc <- lfc %>%
  filter(GENE %in% c(crispr_gene_sets$essential$pan_cancer_Sanger, 
                     crispr_gene_sets$essential$hart_nonessential)) %>%
  mutate(gene_group = ifelse(GENE %in% crispr_gene_sets$essential$pan_cancer_Sanger, "pan_cancer_Sanger","hart_nonessential"))

lfc.pc %>%
  filter(time_point == "day14") %>%
  ggplot(aes(MOI, correctedFC, color = gene_group)) +
  geom_point(position = position_dodge(width=0.75)) +
  geom_boxplot(notch=T) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ggtitle("Day 14: Control vs Plasmid logFC by MOI")

```

## Control guides

```{r}
lfc %>%
  filter(time_point == "day14" & GENE %in% c("Control")) %>%
  mutate(gene_group = "Control") %>%
  ggplot(aes(MOI, correctedFC, color = gene_group)) +
  geom_point(position = position_dodge(width=0.75)) +
  geom_boxplot(notch=T) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  ylim(-2.5,2) + 
  ggtitle("Day 14: Control vs Plasmid logFC by MOI")


qc %>%
    filter(time_point=="day14" & SampleClass!="plasmid") %>%
    ggplot(aes(moi,NNMD_robust.ctrl_plasmid.control_guides,color=moi)) +
    geom_point(cex = 3) +
  geom_hline(yintercept = 0, linetype="dashed") +
    ggtitle("Day 14: logFC differential (NNMD) of Non-targeting Controls")

```

## SD vs MAD

```{r}
lfc %>%
  filter(time_point == "day14") %>%
  group_by(MOI) %>%
  summarise(logFC_MAD = mad(correctedFC),
            logFC_SD = sd(correctedFC)) %>%
  ungroup() %>%
  ggplot(aes(MOI, logFC_SD)) +
  geom_bar(stat = "identity") +
  ggtitle("SD of logFC by MOI")

```

## Delta across time points

```{r}
lfc.moi <- lfc %>%
  filter(time_point == "day14") %>%
  pivot_wider(id_cols = SEQID, names_from = MOI, names_prefix = "logFC_MOI_", values_from = avgFC) %>%
  mutate(logfc_neutral_MOI_0.3 = between(logFC_MOI_0.3,-0.8,0.8),
         abs_delta_logFC_MOI_0.3_2.12 = abs(logFC_MOI_0.3 - logFC_MOI_2.12),
         abs_delta_logFC_MOI_0.3_2.5 = abs(logFC_MOI_0.3 - logFC_MOI_2.5),
         abs_delta_logFC_MOI_0.3_5F = abs(logFC_MOI_0.3 - logFC_MOI_5F),
         abs_delta_logFC_MOI_0.3_0.75 = abs(logFC_MOI_0.3 - logFC_MOI_0.75),
         abs_delta_logFC_MOI_0.3_1 = abs(logFC_MOI_0.3 - logFC_MOI_1),
         elevated_neutral_0.75 = (between(logFC_MOI_0.3,-0.8,0.8) & abs_delta_logFC_MOI_0.3_0.75 > 2),
         elevated_neutral_1 = (between(logFC_MOI_0.3,-0.8,0.8) & abs_delta_logFC_MOI_0.3_1 > 2),
         elevated_neutral_2.12 = (between(logFC_MOI_0.3,-0.8,0.8) & abs_delta_logFC_MOI_0.3_2.12 > 2),
         elevated_neutral_2.5 = (between(logFC_MOI_0.3,-0.8,0.8) & abs_delta_logFC_MOI_0.3_2.5 > 2),
         elevated_neutral_5F = (between(logFC_MOI_0.3,-0.8,0.8) & abs_delta_logFC_MOI_0.3_5F > 2),
         elevated_2.5_5F = (elevated_neutral_2.5 & elevated_neutral_5F),
         elevated_either_2.5_5F = (elevated_neutral_2.5 | elevated_neutral_5F)) %>%
  left_join(lib, by = c("SEQID" = "V2"))


lfc.moi %>%
  mutate(abs_delta_logFC_MOI_0.3_2.12 = abs(logFC_MOI_0.3 - logFC_MOI_2.12)) %>%
  ggplot(aes(logFC_MOI_0.3, abs_delta_logFC_MOI_0.3_2.12)) +
  geom_hex() +
  geom_smooth() +
  geom_vline(xintercept = 0, linetype="dashed") +
  ggtitle("logFC Delta: MOI 0.3 vs MOI 2.12")


lfc.moi%>%filter(logfc_neutral_MOI_0.3) %>%
  ggplot(aes(logFC_MOI_2.5,logFC_MOI_5F)) +
  geom_hex() +
  geom_point(data = lfc.moi %>% filter(elevated_neutral_2.5), aes(color = "elevated_2.5")) + 
  geom_point(data = lfc.moi %>% filter(elevated_neutral_5F), aes(color = "elevated_5F")) + 
  geom_point(data = lfc.moi %>% filter(elevated_2.5_5F), aes(color = "elevated_both")) + 
  geom_smooth() +
  geom_hline(yintercept = 0.8,color="red") +
  geom_hline(yintercept = -0.8,color="red") +
  geom_vline(xintercept = -0.8,color="red") +
  geom_vline(xintercept = 0.8,color="red")

```

## RNApol III speed (using RNApol II yeast estimates)

```{r}
extract_5mer_counts <- function(seqs){
  five_mers <- as.data.frame(table(c(sapply(seqs, function(x) substring(x,1:(19-5+1),5:19))))) %>%
    rename(five_mer = Var1, count = Freq) %>%
    mutate(frequency = count/sum(count))
  return(five_mers)
}

five_mers.day14_moi2.5 <- rbind(extract_5mer_counts(lfc.moi$V1[(lfc.moi$elevated_neutral_2.5 | lfc.moi$elevated_neutral_5F)]) %>%
                                  mutate(type = "depleted_neutral"),
                                extract_5mer_counts(lfc.moi$V1[(!lfc.moi$elevated_neutral_2.5 & !lfc.moi$elevated_neutral_5F)]) %>%
                                  mutate(type = "not_depleted"),
                                extract_5mer_counts(sample(lfc.moi$V1, 309, replace = F)) %>%
                                  mutate(type = "random"))

```

```{r}
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

fivemer_rnap_speed <- function(seq, type = "mttr", pos = 1){
  fm <- c(sapply(seq, function(x) substring(x,1:(19-5+1),5:19)))
  rnap_dens <- rnap_fivemer$With.0.WO.Pauses.1[match(fm, rnap_fivemer$five_mer)]
  if(type == "median"){
    return(median(rnap_dens, na.rm=T))
  }else if(type == "mean"){
    return(mean(rnap_dens, na.rm=T))
  }else if(type == "mttr"){
    return(gm_mean(1/rnap_dens))
  }else if(type == "sd"){
    return(sd(1/rnap_dens))
  }else if(type == "first"){
    return(1/rnap_dens[1])
  }else if(type == "last"){
    return(1/rnap_dens[length(rnap_dens)])
  }else if(type == "pos"){
    return(1/rnap_dens[pos])
  }else if(type == "dcor"){
    return(energy::dcor2d(1:length(rnap_dens),1/rnap_dens,type="U"))
  }
}


lfc.moi %<>%
  rowwise() %>%
  mutate(#rnap_speed.MTTR = fivemer_rnap_speed(V1, type = "mttr"),
         #rnap_speed.SD = fivemer_rnap_speed(V1, type = "sd"),
         rnap_speed.1 = fivemer_rnap_speed(V1, type = "pos"),
         rnap_speed.2 = fivemer_rnap_speed(V1, type = "pos", pos=2),
         rnap_speed.3 = fivemer_rnap_speed(V1, type = "pos", pos=3),
         rnap_speed.4 = fivemer_rnap_speed(V1, type = "pos", pos=4),
         rnap_speed.5 = fivemer_rnap_speed(V1, type = "pos", pos=5),
         rnap_speed.6 = fivemer_rnap_speed(V1, type = "pos", pos=6),
         rnap_speed.7 = fivemer_rnap_speed(V1, type = "pos", pos=7),
         rnap_speed.8 = fivemer_rnap_speed(V1, type = "pos", pos=8),
         rnap_speed.9 = fivemer_rnap_speed(V1, type = "pos", pos=9),
         rnap_speed.10 = fivemer_rnap_speed(V1, type = "pos", pos=10),
         rnap_speed.11 = fivemer_rnap_speed(V1, type = "pos", pos=11),
         rnap_speed.12 = fivemer_rnap_speed(V1, type = "pos", pos=12),
         rnap_speed.13 = fivemer_rnap_speed(V1, type = "pos", pos=13),
         rnap_speed.14 = fivemer_rnap_speed(V1, type = "pos", pos=14),
         rnap_speed.15 = fivemer_rnap_speed(V1, type = "pos", pos=15)) %>%
  ungroup


rnap_sp.bases <- lfc.moi %>%
  pivot_longer(starts_with("rnap_speed."), names_to = "fivemer_position", values_to = "RNApol_speed") %>%
  rowwise() %>%
  mutate(fivemer_position = as.integer(gsub("^\\D+?\\.(\\d+)$","\\1",fivemer_position))) %>%
  ungroup

rnap_sp.bases.av <- rnap_sp.bases %>%
  group_by(elevated_either_2.5_5F, fivemer_position) %>%
  summarise(RNApol_speed.mean = mean(RNApol_speed)) %>%
  ungroup

```


## logFC shrinkage

```{r}
# Estimate standard error for individual sgRNA logFC values.
calc_lfc_SE <- function(data, plasmid, comp){
  pl <- sym(plasmid)
  comp_1 <- sym(comp[1])
  comp_2 <- sym(comp[2])
  data %<>%
    mutate(lfc_1 = log2(!!comp_1 + 5) - log2(!!pl + 5),
           lfc_2 = log2(!!comp_2 + 5) - log2(!!pl + 5),
           # Don't want SErrors of 0 (can't be shrunk by ashr).
           lfc_1 = ifelse(lfc_1 == lfc_2, lfc_1 + 1, lfc_1),
           lfcSE = sd(c(lfc_1,lfc_2))/sqrt(2))
  return(data)
}

# MOI 0.3
lfc.0.3.d14 <- counts %>%
  filter(comparison == "MOI-0.3-day14") %>%
  select(sample_id, sgRNA, gene, count) %>%
  pivot_wider(id_cols = c(sgRNA,gene), names_from = sample_id, values_from = count) %>%
  fgcQC::normalize_library_depth_median_ratio() %>%
  fgcQC::calc_log2_fold_change_gRNAs(ref = "TECHDEV0001_plasmid", comp = c("TECHDEV0001_01_01_29","TECHDEV0001_01_01_30")) %>%
  rowwise() %>%
  calc_lfc_SE(., "TECHDEV0001_plasmid", c("TECHDEV0001_01_01_29","TECHDEV0001_01_01_30")) %>%
  ungroup

lfc.0.3.d14.ash <- ash(lfc.0.3.d14$log2FC, lfc.0.3.d14$lfcSE)

lfc.0.3.d14 %<>%
  mutate(log2FC.shrink = lfc.0.3.d14.ash$result$PosteriorMean,
         gene_group = case_when(gene %in% crispr_gene_sets$essential$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                gene %in% crispr_gene_sets$essential$hart_nonessential ~ "hart_nonessential",
                                TRUE ~ "other")) %>%
  rowwise() %>%
  mutate(avgCount = mean(c(mean(c(TECHDEV0001_01_01_29,TECHDEV0001_01_01_30)),TECHDEV0001_plasmid))) %>%
  ungroup

# MOI 2.5
lfc.2.5.d14 <- counts %>%
  filter(comparison == "MOI-2.5-day14") %>%
  select(sample_id, sgRNA, gene, count) %>%
  pivot_wider(id_cols = c(sgRNA,gene), names_from = sample_id, values_from = count) %>%
  fgcQC::normalize_library_depth_median_ratio() %>%
  fgcQC::calc_log2_fold_change_gRNAs(ref = "TECHDEV0001_plasmid", comp = c("TECHDEV0001_01_01_37","TECHDEV0001_01_01_38")) %>%
  rowwise() %>%
  calc_lfc_SE(., "TECHDEV0001_plasmid", c("TECHDEV0001_01_01_37","TECHDEV0001_01_01_38")) %>%
  ungroup

lfc.2.5.d14.ash <- ash(lfc.2.5.d14$log2FC, lfc.2.5.d14$lfcSE)

lfc.2.5.d14 %<>%
  mutate(log2FC.shrink = lfc.2.5.d14.ash$result$PosteriorMean,
         gene_group = case_when(gene %in% crispr_gene_sets$essential$pan_cancer_Sanger ~ "pan_cancer_Sanger",
                                gene %in% crispr_gene_sets$essential$hart_nonessential ~ "hart_nonessential",
                                TRUE ~ "other")) %>%
  rowwise() %>%
  mutate(avgCount = mean(c(mean(c(TECHDEV0001_01_01_37,TECHDEV0001_01_01_38)),TECHDEV0001_plasmid))) %>%
  ungroup


```


# GICC

```{r}
qc %>%
  filter(time_point=="day14" & SampleClass!="plasmid") %>%
  ggplot(aes(moi,GICC.ctrl_plasmid.hart_nonessential,color=moi)) +
  geom_point(cex = 3) +
  ggtitle("Day 14: reproducibility of counts of non-essentials")

```

# Appendix

## MOI empirical

```{r}
p1 <- qc %>%
  filter(time_point == "day14") %>%
  ggplot(aes(x=MOI, y=NNMD_robust.ctrl_plasmid.pan_cancer_Sanger)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype="dashed") +
  geom_smooth(method = "nls",
              formula = y ~ A - (A/(1+exp(-x*B))^(1/v)),
              method.args = list(start = c(A = -6.5, B = 2, v = 1.2)),
              se=F) +
  ggtitle("Day 14: logFC effect size (NNMD) essential vs nonessential")

```


## MOI theoretical 

```{r}
prob_pairing_non_neutral_guide <- function(moi, pe){
  # max number of viruses per cell (at MOI of 5, ppois(20,5,lower.tail = F) < 1e-7)
  max_n <- 20
  n <- 2:max_n
  ret <- NULL
  for(i in n){
    pb_nonzero <- 1 - dbinom(0, i, pe)
    ret <- append(ret, dpois(i, moi) * pb_nonzero)
  }
  return(sum(ret))
}

moi <- c(0.3, 0.75, 1, 2.12, 2.5, 5)
ppair <- sapply(moi, prob_pairing_non_neutral_guide, 0.1)

data.frame(MOI = moi, prob_pair_ess = ppair) %>%
  ggplot(aes(MOI, prob_pair_ess)) +
  geom_point() +
  geom_smooth(method = "lm",
              formula = y ~ splines2::bSpline(x, df = 3),
              se=F)

```


